# Generated by Django 4.2.6 on 2023-10-18 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('item', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=100)),
                ('item_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('location', models.AutoField(primary_key=True, serialize=False)),
                ('location_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='purchase_orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('pending', 'Pending'), ('requested', 'Requested'), ('ordered', 'Ordered')], verbose_name=15)),
            ],
        ),
        migrations.CreateModel(
            name='units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='vendors',
            fields=[
                ('vendor', models.AutoField(primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='purchase_reference',
            fields=[
                ('purchase_reference', models.AutoField(primary_key=True, serialize=False)),
                ('catalog', models.CharField(max_length=25)),
                ('price', models.PositiveSmallIntegerField()),
                ('amount', models.PositiveSmallIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.items')),
                ('unit', models.ForeignKey(on_delete=models.SET('unit(s)'), to='inventory.units')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.vendors')),
            ],
        ),
        migrations.CreateModel(
            name='on_request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('pending', 'Pending'), ('requested', 'Requested'), ('ordered', 'Ordered')], max_length=15)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.items')),
                ('unit', models.ForeignKey(on_delete=models.SET('unit(s)'), to='inventory.units')),
            ],
        ),
        migrations.CreateModel(
            name='on_order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('approved', 'Approved'), ('pending', 'Pending'), ('requested', 'Requested'), ('ordered', 'Ordered')], max_length=15)),
                ('date', models.DateField(null=True)),
                ('po', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.purchase_orders')),
                ('purchase_reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.purchase_reference')),
            ],
        ),
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('inventory', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.PositiveSmallIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.items')),
                ('location_name', models.ForeignKey(on_delete=models.SET('Lab'), to='inventory.location')),
                ('unit', models.ForeignKey(on_delete=models.SET('unit(s)'), to='inventory.units')),
            ],
        ),
    ]
