# Generated by Django 4.2.6 on 2023-10-22 23:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="items",
            new_name="item",
        ),
        migrations.RenameModel(
            old_name="units",
            new_name="unit",
        ),
        migrations.RenameModel(
            old_name="vendors",
            new_name="vendor",
        ),
        migrations.AlterModelOptions(
            name="inventory",
            options={"verbose_name": "Inventory", "verbose_name_plural": "Inventory"},
        ),
        migrations.AlterModelOptions(
            name="on_order",
            options={"verbose_name": "Ordered", "verbose_name_plural": "Ordered"},
        ),
        migrations.AlterModelOptions(
            name="on_request",
            options={"verbose_name": "Request", "verbose_name_plural": "Requests"},
        ),
        migrations.AlterModelOptions(
            name="purchase_orders",
            options={
                "verbose_name": "Purchase Order",
                "verbose_name_plural": "Purchase Orders",
            },
        ),
        migrations.AlterModelOptions(
            name="purchase_reference",
            options={
                "verbose_name": "Purchase Reference",
                "verbose_name_plural": "Purchase References",
            },
        ),
    ]
